### ISSUE TITLE
Took Tweaking to Work on OS X

### ISSUE THREAD

**Issue by demastrie** [breunigs/duplicity-acdcli#1]
It's great that we now have this duplicity acd backend. I just wanted to note for others that I had to install to _/usr/local/Cellar/duplicity/0.6.25_1/libexec/lib/python2.7/site-packages/duplicity/backends_ instead of the location in the doc. Also, I had to rename all the functions in the acd backend by removing the leading weak method underscores. If I didn't do this modification, I got a _NotImplementedError()_ from backend.py. I only know Python well enough to be dangerous, so I have no idea why this is so...unless it's the version of Duplicity that I'm on (0.6.25_1 from Homebrew). Anyhow, seems to be working now.

**Comment by breunigs** [comment]
Hm, can you try again with a more recent version of duplicity? I'm using 0.7+ some such, so I guess that could be the reason for the _problem. I will add the different path to the read me.

**Comment by demastrie** [comment]
I worked through the challenge of installing the latest version of duplicity 0.7 on my Mac. Your backend worked as written there. The installation location on my Mac was _/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/duplicity/backends_. FWIW, the backend worked well with the method renaming on 0.6-latest. Nice job to you and the originator. Getting my $60/yr worth out of ACD now: storage (acdcli) plus backup (duplicity). Just need to figure out sync and share and I'll have my plan implemented.  :)

**Comment by gabrielke** [comment]
Can you please create a version that works with duplicity 0.6?

**Comment by breunigs** [comment]
You can just place the acdbackend.py file into the correct folder, like the one mentioned above. If the path is different on your system, you need to refer to your system documentation to find where the backends folder of duplicity is.

**Comment by breunigs** [comment]
Ah well, and remove the underscores from the methods. I totally forgot about that

But I will not put the effort towards making it compatible with an outdated version, I really do not have the time. I guess you can always fork the repo...

**Comment by kwloafman** [comment]
The best option is to update to a modern version.

...Ken

**Comment by gabrielke** [comment]
Well I'm using this on a Debian Jessie (Proxmox 3.4) installation.
In the meantime I figured out, I'll prepare something meaningful.

**Comment by breunigs** [comment]
Duplicity 0.7+ is available in Jessie backports, so that should integrate fairly easily: https://packages.debian.org/jessie-backports/duplicity 

In any case, I consider the master branch dead anyway since I have a working implementation that directly talks to ACD. I'm just waiting on Amazon to bestow the consumer with production usage limits, but so far they didn't ping me back :(.
