### ISSUE TITLE
AttributeError Problem

### ISSUE THREAD

**Issue by Punkado** [breunigs/duplicity-acdcli#4]
Hello,

I am trying to setup the duplicity-acdcli and i i am having a problem that i cant figure out why.

The acd_cli is working without a problem, but when i try to run the duplicity-acdcli i get this error:

duplicity wallpaper acd:///backup/my_new_backup/
Traceback (most recent call last):
  File "/usr/bin/duplicity", line 1537, in <module>
    with_tempdir(main)
  File "/usr/bin/duplicity", line 1531, in with_tempdir
    fn()
  File "/usr/bin/duplicity", line 1369, in main
    action = commandline.ProcessCommandLine(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/duplicity/commandline.py", line 1117, in ProcessCommandLine
    backup, local_pathname = set_backend(args[0], args[1])
  File "/usr/lib/python2.7/site-packages/duplicity/commandline.py", line 1006, in set_backend
    globals.backend = backend.get_backend(bend)
  File "/usr/lib/python2.7/site-packages/duplicity/backend.py", line 223, in get_backend
    obj = get_backend_object(url_string)
  File "/usr/lib/python2.7/site-packages/duplicity/backend.py", line 209, in get_backend_object
    return factory(pu)
  File "/usr/lib/python2.7/site-packages/duplicity/backends/amazonclouddrivebackend.py", line 40, in __init__
    if self.which(self.acd_cmd) == None:
AttributeError: 'ACDBackend' object has no attribute 'which'

The problem occur in my machine (Arch, duplicity 0.7.07) and also in my server (Debian, duplicity 0.7.07.1).

Maybe is a simple python problem, but my knowledge in python is very low.

Thanks!

**Comment by maxha651** [comment]
Hi! Kind of weird that we reported the same issue at the same time :)

Anyway, I'm not the maintainer, but created a pull request that works for me if you want to try it out at #6.

Regards
Max

**Comment by Punkado** [comment]
Hey Maxha651,

Yes, weird! But also good that you solve the problem, at least for you... For me now i have other error:

UnsupportedBackendScheme: scheme not supported in url: acd:///backup/my_new_backup/

How you are passing the URL?

Thanks

**Comment by Punkado** [comment]
Hey, 

Nevermind, worked when i used your  amazonclouddrivebackend.py, not only the 2 changes... So maybe you modified something else...

Anyway, thanks, is working now.

**Comment by maxha651** [comment]
Glad you got it working :)

**Comment by breunigs** [comment]
@Punkado I am not sure which version you are using now, but please be aware that duplicity now ships with a variant of this backend. It's available as `acd+acdcli:///` and compatible with this one, so you just need to append `+acdcli` to your backup path and that's it. 

While this variant will likely continue to work, all future patches should be sent directly upstream. Using the bundled version also should prevent failures due to minor changes, like this one.

Cheers
Stefan
