### ISSUE TITLE
Crashes on missing attribute with duplicity 0.7.07

### ISSUE THREAD

**Issue by maxha651** [breunigs/duplicity-acdcli#5]
Hi! Great work with this!

I got this stack trace:

```
Traceback (most recent call last):
  File "/bin/duplicity", line 1537, in <module>
    with_tempdir(main)
  File "/bin/duplicity", line 1531, in with_tempdir
    fn()
  File "/bin/duplicity", line 1369, in main
    action = commandline.ProcessCommandLine(sys.argv[1:])
  File "/usr/lib64/python2.7/site-packages/duplicity/commandline.py", line 1117, in ProcessCommandLine
    backup, local_pathname = set_backend(args[0], args[1])
  File "/usr/lib64/python2.7/site-packages/duplicity/commandline.py", line 1006, in set_backend
    globals.backend = backend.get_backend(bend)
  File "/usr/lib64/python2.7/site-packages/duplicity/backend.py", line 223, in get_backend
    obj = get_backend_object(url_string)
  File "/usr/lib64/python2.7/site-packages/duplicity/backend.py", line 209, in get_backend_object
    return factory(pu)
  File "/usr/lib64/python2.7/site-packages/duplicity/backends/amazonclouddrivebackend.py", line 40, in __init__
    if self.which(self.acd_cmd) == None:
AttributeError: 'ACDBackend' object has no attribute 'which'
```

It worked yesterday so it might have been a new duplicity version which broke it. This is with duplicity version 0.7.07. Just replacing self.which with util.which from duplicity.util seems to work fine though. 

Also noticed that this backend actually came with this duplicity version under a different name (acdclibackend). Is there any difference between the two? This repo still seems pretty updated. Perhaps add something to the README about this? 

Regards
Max

**Comment by breunigs** [comment]
Can you test if the version shipped with duplicity works without any changes? If so, I strongly recommend to switch to the bundled variant.

There is little differences between the two versions, as it was merged to upstream in February: http://bazaar.launchpad.net/~duplicity-team/duplicity/0.7-series/revision/1192

**Comment by breunigs** [comment]
(of course, you need to adjust the URL to look like `acd+acdcli:///the/path`

**Comment by maxha651** [comment]
As you say, there's not much difference between the two so I don't think there'll be any trouble switching. I'll switch to using acd+acdcli and let you know if anything breaks. Right now the other script is running so I'll probably let that one run it's course before switching.

**Comment by maxha651** [comment]
But as I mentioned I think it would be a good idea to add something about this being bundled with 0.7.07 and the acd -> acd+acdcli switch to README since I think people will keep using this one otherwise :)

**Comment by breunigs** [comment]
I had to adapt your patch so it continues working in the old version.

I will add deprecation warnings and upgrade tutorials soon.

**Comment by maxha651** [comment]
Sounds good :)
