### ISSUE TITLE
Hangs when calling acd_cli sync

### ISSUE THREAD

**Issue by hen5599** [breunigs/duplicity-acdcli#7]
[Sent this to duplicity mailing list, but wasn't sure if I need to create issue here to get attention of someone more familiar with this backend's code, sorry for the cross-post]

I've just installed duplicity 0.7.07.1 with hopes of using Amazon Cloud Drive as the backend.

I completed the setup as described in the documentation of acd_cli and it seems operational.

When using duplicity, however, once it enters the acdcli backend and calls sync, it simply hangs.

I don't know too much python, but took a look at the backend:
/usr/local/lib/python2.7/dist-packages/duplicity/backends/acdclibackend.py

I added the -v flag to the sync command on line 60 and placed a log.Info() test output before and after this line, but it still hangs with no output (beyond my "Calling sync" info output) and the acd_cli log file also silent:

log.Info("Calling sync")
self.subprocess_popen(self.acd_cmd + " -v sync")
log.Info("Finished sync")

I ran acd_cli sync manually on the command line and it succeeds normally, so why does it hang inside of duplicity? Is there a way to make python say more what's going on when it goes to self.subprocess_popen()?

**Comment by breunigs** [comment]
You are probably running duplicity with a different user than when you normally run acdcli. It then waits for you to input data, which is not possible through duplicity. If that's the case, either copy acdcli s config or set it up regularly as the backup user.

Other than that, ACD has issues right Now, so maybe that's related. Try uploading/downloading files with acd cli to test.

**Comment by hen5599** [comment]
Hi, thanks for the fast reply. I'm running all commands as root (since duplicity runs as root).

As mentioned, direct acd_cli commands on the command line work fine.

I do use ACD_CLI_CACHE environment variable to point to a custom cache location, but even if I remove that, it still does nothing (because there is no acd_cli log output and nothing on STDOUT, it doesn't look like it even gets far enough to talk to ACD).

**Comment by breunigs** [comment]
Hrm, I am a bit stumped.

Once it starts hanging, does acdcli show up in the process list (`ps aux`)? If not, what happens when you try to run something like `subprocess("env > /temp/debug")` to see if any environment variables are setup weirdly? I am on mobile, so the exact call looks slightly differently.

If nothing sticks, you can also try your luck with new version in the `direct` branch repository which directly talks to ACD. Untested and not sure if my keys are already valid.

**Comment by hen5599** [comment]
Ah, no, I was slightly mistaken. The problem was a misspelled environment variable name for ACD_CLI_CACHE_PATH. Thanks for the great tool!

**Comment by hen5599** [comment]
Just out of curiosity, you've re-engineered the code so that it no longer uses acd_cli? Will that be part of the new duplictiy package as well? One less dependency sounds great.

**Comment by breunigs** [comment]
Yes for the rewrite. And yes, i plan to send the patch upstream, but it needs more testing before I can do that.

**Comment by hen5599** [comment]
Please make an announcement on the duplicity mailing list when it's ready for testing! I had to install python3 JUST for acd_cli which I rather not do. I look forward to your rewrite.

PS - Do you happen to know, can I copy the ACD_CLI_CACHE_PATH credentials (just client_data file?) to other machines to have it work without having to run the init/registration process on every machine?  (is the init just per-app?  or is it per-client?)

**Comment by breunigs** [comment]
yes, the credentials are copy&pasteable as far as I know.

Also, the code is ready for testing. The only thing missing is production limits on the keys used and for that I probably need to submit the changes… somehow. But everything else: feel free to test. I wanted to dogfood it for some weeks before sending it upstream.
