### ISSUE TITLE
Create folder if it does not exist

### ISSUE THREAD

**Issue by gabrielke** [breunigs/duplicity-acdcli#8]
Would be nice if this backend (just like ftp backend) would create the directory/directories on the target if they do not exist yet.

**Comment by breunigs** [comment]
It already works like that for the direct backend, so nothing to do there.

You are right for the backend that uses acd_cli, but that approach is flawed anyway. As such I will not put in any effort into that branch unless its severe bugfixes that would also need to be patched in duplicity itself. So yeah, let's hope Amazon replies sooner than later :)
