### ISSUE TITLE
Cleanup of multiple incomplete backups

### ISSUE THREAD

**Issue by gabrielke** [breunigs/duplicity-acdcli#9]
For one of my sets I had several failed full backups which I wanted to clean with 
clean --force.
But it doesn't work:

duplicity-full.20160719T213004Z.vol505.difftar.gpg**
Traceback (most recent call last):
  File "/usr/bin/duplicity", line 1404, in <module>
    with_tempdir(main)
  File "/usr/bin/duplicity", line 1397, in with_tempdir
    fn()
  File "/usr/bin/duplicity", line 1339, in main
    cleanup(col_stats)
  File "/usr/bin/duplicity", line 792, in cleanup
    col_stats.backend.delete(ext_remote)
  File "/usr/lib/python2.7/dist-packages/duplicity/backends/amazonclouddrivebackend.py", line 132, in delete
    remote_file_path = os.path.join(urllib.unquote(self.parsed_url.path.replace('///', '/')), remote_filename).rstrip()
  File "/usr/lib/python2.7/posixpath.py", line 75, in join
    if b.startswith('/'):
AttributeError: 'list' object has no attribute 'startswith'

23:19:09.351 Task 'CLEANUP' failed with exit code '30'.
--- Finished state FAILED 'code 30' at 23:19:09.351 - Runtime 00:00:08.451 ---

... I guess this is because the _delete function expects a single string but in this case it gets a list.
I checked the newer version has the same logic too.

**Comment by breunigs** [comment]
Please update to duplicity 0.7+ and use either the shipped version or vanilla variant of this backend.

0.7 checks if the plugin supports `_delete_list` and if it doesn't, it loops over the file and asks the backend to delete them individually. For reference, here is the implementation in a GitHub mirror of duplicity: https://github.com/henrysher/duplicity/blob/master/duplicity/backend.py#L575-L586

If you can really reproduce this with 0.7+, please reopen the ticket.
